### PR TITLE
[FEAT] - Add model2vec embedding models

### PR DESCRIPTION
**Pull request by sky-2002**
This PR adds support for static embedding models (smaller and faster models)
After reading the blog post attached below, going through the repo linked below and after trying out those models, I felt that this aligns well with `chonkie`'s "_being lightning-fast and lightweight_" philosophy.

Referred #24 for inheriting from `BaseEmbeddings`

References:
- [Model2Vec repo](https://github.com/MinishLab/model2vec)
- [Blog post](https://minishlab.github.io/tokenlearn_blogpost/) explaining the model used

If there are any speed or performance benchmarks that chonkie uses, please point me to them, happy to test it out.

@bhavnicksm let me know if any questions, or if something needs to be modified (I think the way how chunkers would use this `BaseEmbedding` was not clear to me), looking forward for review

### CODE REVIEW

**Comment by bhavnicksm** [comment]
Hey @sky-2002! 

Thanks for the pull request 😊

I would ask you to wait for a bit, since the Model2Vec page says they support direct loading via SentenceTransformer as well, I hope to test out that capability! Given that Chonkie aims to be a minimal dependency library, if we can continue without an additional dependency, that would be preferable 

I am planning for a `SentenceTransformerEmbeddings` already so maybe we could add this as a `use_static` or `use_model2vec` bool flag that could be passed into it itself. 

Currently I am swamped with tasks, so this might take a while. Sorry for the delay. 😔

Thanks!

**Comment by sky-2002** [comment]
hey no worries, sure you can check, afaik, they need the `model2vec` package even when loading from `sentence_transformers` - see [code here](https://github.com/UKPLab/sentence-transformers/blob/e156f38b1007e7860218c27223e1d577f3a021fe/sentence_transformers/models/StaticEmbedding.py#L203)
Thought that this would help because of the speed and light-weight factors.
But I agree, no extra dependencies needed 🙌🏻 , will try to check for options

**Comment by mrmps** [comment]
I've tried chunking with model2vec, and it's very very good (and MUCH faster). I think once people try it they'll stop using larger embeddings to chunk

**Comment by mrmps** [comment]
Thanks for adding this @sky-2002

**Comment by bhavnicksm** [comment]
Hey @sky-2002! 

I just tested Model2Vec out and it is outstanding! 🤯 The speed is absolutely insane, and the quality is actually pretty decent...

Let's add this to 🦛 Chonkie! 

I just made a couple of changes in #44, #46 and #47, and recently added some info inside the DOCS.md to support new embeddings. Could you have a look? I'd also love if you could add some info about Model2Vec support inside the DOCS.md, it would make it much easier for me to manage...

Thanks!

**Comment by sky-2002** [comment]
> Could you have a look? I'd also love if you could add some info about Model2Vec support inside the DOCS.md, it would make it much easier for me to manage...

Oh okay, I think I started a review at the same time, so missed the msg, I will check `DOCS.md`

**Comment by sky-2002** [comment]
Sure, will do

**Comment by Pringled** [comment]
Hey, one of the model2vec authors here. This is such a cool usecase, can' wait to try it out myself, I just came across Chonkie and it looks amazing! 

Wanted to make one suggestion perhaps for the future: model2vec itself is very lightweight (the base package's only major dependency is numpy in fact, it doesn't depend on Torch or SentenceTransformers for inference), so it might be interesting to use it stand-alone at some point if you want to keep Chonkie as lightweight as possible. If you have any questions or requests do let me know!

**Comment by bhavnicksm** [comment]
Hey @Pringled! 

Thank you for the kind words for Chonkie~!  😊

> Wanted to make one suggestion perhaps for the future: model2vec itself is very lightweight (the base package's only major dependency is numpy in fact, it doesn't depend on Torch or SentenceTransformers for inference), so it might be interesting to use it stand-alone at some point if you want to keep Chonkie as lightweight as possible. If you have any questions or requests do let me know!

Woah! That's pretty cool – Yes, Chonkie would ideally be more light-weight and performant chunking, so Model2Vec seems perfect for it's fast speed and being ultra-lightweight. And, being able to avoid the torch + SentenceTransformer heaviness in the default 'semantic' install would be great!

Thank you for the suggestion, @Pringled!

**Comment by bhavnicksm** [comment]
Hey @sky-2002, 

Sorry to ask you this considering you just refactored your PR, but would you refactor it to be independent of SentenceTransformers, utilizing just Numpy as the dependency?

We can build it as a `Model2VecEmbeddings` independent class, and the `EmbeddingsRegistry` can support the  `minishlab/potion-` series of models from the Model2Vec repository. 

Let me know if you have any questions. 
Thanks!

**Comment by sky-2002** [comment]
Hey @bhavnicksm , I have updated the code. Let me know if any other changes needed.

Also, is there any benchmark that I can try on to check speed/quality tradeoff ?

**Comment by bhavnicksm** [comment]
Hey @sky-2002! 

This PR looks good to merge. Great work, let's go! 🚀 

For the benchmark, I usually use `PaulGrahamEssayDataset` which is essentially a long text file or the `bhavnicksm/fineweb-edu-micro` dataset on Huggingface which is made from a random sample of million tokens from `fineweb-edu` from texts that are at least 1000 GPT2 tokens or longer. 

I'll merge the PR so it can be tested and benchmarked in dev.

Thank you so much and welcome to the Chonkie fam 🦛🫶

**Comment by bhavnicksm** [comment]
Just an update, 

Model2Vec is only about 48 MiB on installation and about 10x faster out of the box for semantic chunking (6ms vs 63ms) compared to SentenceTransformers!

Absolutely amazing to have this in Chonkie!

**Comment by sky-2002** [comment]
> Thank you so much and welcome to the Chonkie fam 🦛🫶

Thanks a lot 🦛🫶, happy to contribute, and thanks for the quick reviews and feedback

**Pull request merged**
